---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "ricoberger"
    assignees:
      - "ricoberger"
    labels:
      - "changelog: changed"
    groups:
      github-actions:
        patterns:
          - "*"

  - package-ecosystem: "docker"
    directory: "/cmd/echoserver"
    schedule:
      interval: "monthly"
    reviewers:
      - "ricoberger"
    assignees:
      - "ricoberger"
    labels:
      - "changelog: changed"
    groups:
      docker:
        patterns:
          - "*"

  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "ricoberger"
    assignees:
      - "ricoberger"
    labels:
      - "changelog: changed"
    groups:
      gomod:
        patterns:
          - "*"
