// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: proto/echoserver.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EchoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoRequest) Reset() {
	*x = EchoRequest{}
	mi := &file_proto_echoserver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoRequest) ProtoMessage() {}

func (x *EchoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_echoserver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoRequest.ProtoReflect.Descriptor instead.
func (*EchoRequest) Descriptor() ([]byte, []int) {
	return file_proto_echoserver_proto_rawDescGZIP(), []int{0}
}

func (x *EchoRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type EchoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EchoResponse) Reset() {
	*x = EchoResponse{}
	mi := &file_proto_echoserver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EchoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EchoResponse) ProtoMessage() {}

func (x *EchoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_echoserver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EchoResponse.ProtoReflect.Descriptor instead.
func (*EchoResponse) Descriptor() ([]byte, []int) {
	return file_proto_echoserver_proto_rawDescGZIP(), []int{1}
}

func (x *EchoResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type StatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusRequest) Reset() {
	*x = StatusRequest{}
	mi := &file_proto_echoserver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusRequest) ProtoMessage() {}

func (x *StatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_echoserver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusRequest.ProtoReflect.Descriptor instead.
func (*StatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_echoserver_proto_rawDescGZIP(), []int{2}
}

func (x *StatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_proto_echoserver_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_echoserver_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_echoserver_proto_rawDescGZIP(), []int{3}
}

type RequestRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uri           string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	Method        string                 `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Headers       map[string]string      `protobuf:"bytes,4,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestRequest) Reset() {
	*x = RequestRequest{}
	mi := &file_proto_echoserver_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestRequest) ProtoMessage() {}

func (x *RequestRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_echoserver_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestRequest.ProtoReflect.Descriptor instead.
func (*RequestRequest) Descriptor() ([]byte, []int) {
	return file_proto_echoserver_proto_rawDescGZIP(), []int{4}
}

func (x *RequestRequest) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *RequestRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *RequestRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RequestRequest) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

type RequestResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestResponse) Reset() {
	*x = RequestResponse{}
	mi := &file_proto_echoserver_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestResponse) ProtoMessage() {}

func (x *RequestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_echoserver_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestResponse.ProtoReflect.Descriptor instead.
func (*RequestResponse) Descriptor() ([]byte, []int) {
	return file_proto_echoserver_proto_rawDescGZIP(), []int{5}
}

func (x *RequestResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type SimulateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Duration      string                 `protobuf:"bytes,2,opt,name=duration,proto3" json:"duration,omitempty"`
	Size          int64                  `protobuf:"varint,3,opt,name=size,proto3" json:"size,omitempty"`
	Count         int64                  `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	Workers       int64                  `protobuf:"varint,5,opt,name=workers,proto3" json:"workers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimulateRequest) Reset() {
	*x = SimulateRequest{}
	mi := &file_proto_echoserver_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulateRequest) ProtoMessage() {}

func (x *SimulateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_echoserver_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulateRequest.ProtoReflect.Descriptor instead.
func (*SimulateRequest) Descriptor() ([]byte, []int) {
	return file_proto_echoserver_proto_rawDescGZIP(), []int{6}
}

func (x *SimulateRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SimulateRequest) GetDuration() string {
	if x != nil {
		return x.Duration
	}
	return ""
}

func (x *SimulateRequest) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *SimulateRequest) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *SimulateRequest) GetWorkers() int64 {
	if x != nil {
		return x.Workers
	}
	return 0
}

type SimulateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SimulateResponse) Reset() {
	*x = SimulateResponse{}
	mi := &file_proto_echoserver_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SimulateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SimulateResponse) ProtoMessage() {}

func (x *SimulateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_echoserver_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SimulateResponse.ProtoReflect.Descriptor instead.
func (*SimulateResponse) Descriptor() ([]byte, []int) {
	return file_proto_echoserver_proto_rawDescGZIP(), []int{7}
}

func (x *SimulateResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_proto_echoserver_proto protoreflect.FileDescriptor

const file_proto_echoserver_proto_rawDesc = "" +
	"\n" +
	"\x16proto/echoserver.proto\"'\n" +
	"\vEchoRequest\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"(\n" +
	"\fEchoResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"'\n" +
	"\rStatusRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\x10\n" +
	"\x0eStatusResponse\"\xc8\x01\n" +
	"\x0eRequestRequest\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\x12\x16\n" +
	"\x06method\x18\x02 \x01(\tR\x06method\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x126\n" +
	"\aheaders\x18\x04 \x03(\v2\x1c.RequestRequest.HeadersEntryR\aheaders\x1a:\n" +
	"\fHeadersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"+\n" +
	"\x0fRequestResponse\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x85\x01\n" +
	"\x0fSimulateRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x1a\n" +
	"\bduration\x18\x02 \x01(\tR\bduration\x12\x12\n" +
	"\x04size\x18\x03 \x01(\x03R\x04size\x12\x14\n" +
	"\x05count\x18\x04 \x01(\x03R\x05count\x12\x18\n" +
	"\aworkers\x18\x05 \x01(\x03R\aworkers\",\n" +
	"\x10SimulateResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage2\xc3\x01\n" +
	"\n" +
	"Echoserver\x12%\n" +
	"\x04Echo\x12\f.EchoRequest\x1a\r.EchoResponse\"\x00\x12+\n" +
	"\x06Status\x12\x0e.StatusRequest\x1a\x0f.StatusResponse\"\x00\x12.\n" +
	"\aRequest\x12\x0f.RequestRequest\x1a\x10.RequestResponse\"\x00\x121\n" +
	"\bSimulate\x12\x10.SimulateRequest\x1a\x11.SimulateResponse\"\x00B7Z5github.com/ricoberger/echoserver/pkg/grpcserver/protob\x06proto3"

var (
	file_proto_echoserver_proto_rawDescOnce sync.Once
	file_proto_echoserver_proto_rawDescData []byte
)

func file_proto_echoserver_proto_rawDescGZIP() []byte {
	file_proto_echoserver_proto_rawDescOnce.Do(func() {
		file_proto_echoserver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_echoserver_proto_rawDesc), len(file_proto_echoserver_proto_rawDesc)))
	})
	return file_proto_echoserver_proto_rawDescData
}

var file_proto_echoserver_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_echoserver_proto_goTypes = []any{
	(*EchoRequest)(nil),      // 0: EchoRequest
	(*EchoResponse)(nil),     // 1: EchoResponse
	(*StatusRequest)(nil),    // 2: StatusRequest
	(*StatusResponse)(nil),   // 3: StatusResponse
	(*RequestRequest)(nil),   // 4: RequestRequest
	(*RequestResponse)(nil),  // 5: RequestResponse
	(*SimulateRequest)(nil),  // 6: SimulateRequest
	(*SimulateResponse)(nil), // 7: SimulateResponse
	nil,                      // 8: RequestRequest.HeadersEntry
}
var file_proto_echoserver_proto_depIdxs = []int32{
	8, // 0: RequestRequest.headers:type_name -> RequestRequest.HeadersEntry
	0, // 1: Echoserver.Echo:input_type -> EchoRequest
	2, // 2: Echoserver.Status:input_type -> StatusRequest
	4, // 3: Echoserver.Request:input_type -> RequestRequest
	6, // 4: Echoserver.Simulate:input_type -> SimulateRequest
	1, // 5: Echoserver.Echo:output_type -> EchoResponse
	3, // 6: Echoserver.Status:output_type -> StatusResponse
	5, // 7: Echoserver.Request:output_type -> RequestResponse
	7, // 8: Echoserver.Simulate:output_type -> SimulateResponse
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_echoserver_proto_init() }
func file_proto_echoserver_proto_init() {
	if File_proto_echoserver_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_echoserver_proto_rawDesc), len(file_proto_echoserver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_echoserver_proto_goTypes,
		DependencyIndexes: file_proto_echoserver_proto_depIdxs,
		MessageInfos:      file_proto_echoserver_proto_msgTypes,
	}.Build()
	File_proto_echoserver_proto = out.File
	file_proto_echoserver_proto_goTypes = nil
	file_proto_echoserver_proto_depIdxs = nil
}
