// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: proto/echoserver.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Echoserver_Echo_FullMethodName    = "/Echoserver/Echo"
	Echoserver_Status_FullMethodName  = "/Echoserver/Status"
	Echoserver_Request_FullMethodName = "/Echoserver/Request"
)

// EchoserverClient is the client API for Echoserver service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EchoserverClient interface {
	Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error)
	Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error)
	Request(ctx context.Context, in *RequestRequest, opts ...grpc.CallOption) (*RequestResponse, error)
}

type echoserverClient struct {
	cc grpc.ClientConnInterface
}

func NewEchoserverClient(cc grpc.ClientConnInterface) EchoserverClient {
	return &echoserverClient{cc}
}

func (c *echoserverClient) Echo(ctx context.Context, in *EchoRequest, opts ...grpc.CallOption) (*EchoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EchoResponse)
	err := c.cc.Invoke(ctx, Echoserver_Echo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *echoserverClient) Status(ctx context.Context, in *StatusRequest, opts ...grpc.CallOption) (*StatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatusResponse)
	err := c.cc.Invoke(ctx, Echoserver_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *echoserverClient) Request(ctx context.Context, in *RequestRequest, opts ...grpc.CallOption) (*RequestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestResponse)
	err := c.cc.Invoke(ctx, Echoserver_Request_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EchoserverServer is the server API for Echoserver service.
// All implementations must embed UnimplementedEchoserverServer
// for forward compatibility.
type EchoserverServer interface {
	Echo(context.Context, *EchoRequest) (*EchoResponse, error)
	Status(context.Context, *StatusRequest) (*StatusResponse, error)
	Request(context.Context, *RequestRequest) (*RequestResponse, error)
	mustEmbedUnimplementedEchoserverServer()
}

// UnimplementedEchoserverServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEchoserverServer struct{}

func (UnimplementedEchoserverServer) Echo(context.Context, *EchoRequest) (*EchoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Echo not implemented")
}
func (UnimplementedEchoserverServer) Status(context.Context, *StatusRequest) (*StatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedEchoserverServer) Request(context.Context, *RequestRequest) (*RequestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Request not implemented")
}
func (UnimplementedEchoserverServer) mustEmbedUnimplementedEchoserverServer() {}
func (UnimplementedEchoserverServer) testEmbeddedByValue()                    {}

// UnsafeEchoserverServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EchoserverServer will
// result in compilation errors.
type UnsafeEchoserverServer interface {
	mustEmbedUnimplementedEchoserverServer()
}

func RegisterEchoserverServer(s grpc.ServiceRegistrar, srv EchoserverServer) {
	// If the following call panics, it indicates UnimplementedEchoserverServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Echoserver_ServiceDesc, srv)
}

func _Echoserver_Echo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EchoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EchoserverServer).Echo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Echoserver_Echo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EchoserverServer).Echo(ctx, req.(*EchoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Echoserver_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EchoserverServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Echoserver_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EchoserverServer).Status(ctx, req.(*StatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Echoserver_Request_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EchoserverServer).Request(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Echoserver_Request_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EchoserverServer).Request(ctx, req.(*RequestRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Echoserver_ServiceDesc is the grpc.ServiceDesc for Echoserver service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Echoserver_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Echoserver",
	HandlerType: (*EchoserverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Echo",
			Handler:    _Echoserver_Echo_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _Echoserver_Status_Handler,
		},
		{
			MethodName: "Request",
			Handler:    _Echoserver_Request_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/echoserver.proto",
}
